version: "3.9"

services:
  app:
    container_name: app
    build: .
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

